baseURL: "https://shi-ce.github.io"
title: Ce Shi
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

params:
    description: "My name is Ce Shi (史策, 사책), a lecturer at School of Asian Studies, Beijing International Studies University. "
    author: Ce Shi
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Ce Shi
          subtitle: "My name is Ce Shi (史策, 사책), and I’m a lecturer at School of Asian Studies, Beijing International Studies University. I obtained a Ph.D. in Literature from Korea University in August 2024. My research spans Korean modern literature, comparative literature, digital humanities, and Chinese <i>Dongbei<i> literature. <br>Check out my CV for more information about me."
          imageUrl: "profile.jpg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: CV
              url: https://www.dropbox.com/scl/fi/fylok7zyo857o735zcbtp/CV_20150618.pdf?rlkey=nkgnihni1qymeicegxlfqryri&st=xmwr6sga&dl=0
    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Moritz-Maria von Igelfeld"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
